CREATE TABLE USERS
(
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	username VARCHAR(200),
	password VARCHAR(44),
	salt VARCHAR(12),
	name VARCHAR(2000),
	cpf VARCHAR(14),
	type INTEGER
);

CREATE TABLE ACCESS
(
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	user_id INTEGER NOT NULL,
	date_in VARCHAR(200), 
	date_out VARCHAR(200),
	FOREIGN KEY (user_id) REFERENCES USERS(id)
);

CREATE TABLE COMPANIES
(
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	`set` VARCHAR(200) NOT NULL,
	cnpj VARCHAR(40),
	social_reason VARCHAR(2000),
	business_hours VARCHAR(200),
	maximum_temperature DECIMAL(4,2),
	air_conditioner_hours VARCHAR(200)
);

CREATE TABLE EMPLOYEES
(
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	company_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	access_hour VARCHAR(200),
	permission_temperature TINYINT(1),
	FOREIGN KEY (user_id) REFERENCES USERS(id),
	FOREIGN KEY (company_id) REFERENCES COMPANIES(id)
);
