CREATE TABLE USERS
(
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	username VARCHAR(200),
	password VARCHAR(44),
	salt VARCHAR(12),
	name VARCHAR(2000),
	cpf VARCHAR(14),
	office_hours BIGINT
);

CREATE TABLE ACCESS
(
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	user_id INTEGER NOT NULL,
	date_in BIGINT, 
	date_out BIGINT,
	FOREIGN KEY (user_id) REFERENCES USERS(id)
);